# Generated by Django 4.1.3 on 2023-02-02 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('id_agencia', models.CharField(max_length=30)),
                ('metodo', models.CharField(max_length=60)),
                ('objeto', models.CharField(max_length=30)),
                ('num_licitador', models.CharField(max_length=1000)),
                ('comentarios', models.CharField(max_length=1000)),
                ('comprador', models.CharField(max_length=1000)),
                ('num_compra', models.CharField(max_length=1000)),
                ('concepto', models.CharField(max_length=1000)),
                ('cantidad', models.CharField(max_length=1000)),
                ('fondos', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=1000)),
                ('id_comprador', models.CharField(max_length=1000)),
                ('num_reporte', models.CharField(max_length=1000)),
                ('asignacion', models.CharField(max_length=1000)),
                ('procedencia', models.CharField(max_length=1000)),
                ('proveedor', models.CharField(max_length=1000)),
                ('cuenta', models.CharField(max_length=255)),
                ('alerta', models.BooleanField(default='True')),
                ('fecha_reporte', models.DateField()),
                ('fecha_adjudicacion', models.DateField()),
                ('fecha_recibo', models.DateField()),
            ],
        ),
    ]
