# Generated by Django 4.1.3 on 2023-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha_adjudicacion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='num_reporte',
        ),
        migrations.AlterField(
            model_name='compra',
            name='alerta',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_recibo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_reporte',
            field=models.DateField(blank=True),
        ),
    ]
