# Generated by Django 4.1.3 on 2023-03-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_remove_compra_fecha_adjudicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='agencia_id',
            new_name='compra_id',
        ),
    ]
