# Generated by Django 4.1.3 on 2023-03-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_rename_agencia_id_compra_compra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='alerta',
        ),
    ]
