# Generated by Django 4.1.3 on 2023-03-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_compra_alerta_alter_compra_objeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='alerta',
        ),
    ]
