# Generated by Django 4.1.3 on 2023-03-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_alter_compra_asignacion_alter_compra_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='concepto',
            field=models.CharField(blank=True, choices=[('1', 'Nomina'), ('2', 'Facilidades y Servicios Publicos'), ('3', 'Servicios Comprados'), ('4', 'Donativos y Subsidios'), ('5', 'Gastos de Transportacion y Substinencia'), ('6', 'Servicios Profesionales'), ('7', 'Otros Gastos'), ('8', 'Inversion en Mejoras Permanentes'), ('9', 'Amortizacion de la Deuda'), ('10', 'Materiales y Suministros'), ('11', 'Compra de Equipo'), ('12', 'Anuncios y Pautas en Medios'), ('13', 'Incentivos y Subsidios Bienestar Ciudadano'), ('15', 'Aportaciones a Entidades No Gubernamentales'), ('16', 'Asignaciones Englobadas'), ('17', 'Pareo Fondos Federales'), ('18', 'Deudas de Años Anteriores')], max_length=1000),
        ),
    ]
